name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    steps:
    - uses: actions/checkout@v2

    - name: Get specific version CMake, v3.21.2
      uses: lukka/get-cmake@v3.21.2

    - name: Get Boost
      uses: MarkusJx/install-boost@v2.0.0
      id: install-boost
      with:
        # REQUIRED: Specify the required boost version
        # A list of supported versions can be found here: 
        # https://github.com/actions/boost-versions/blob/main/versions-manifest.json
        boost_version: 1.73.0

    - uses: actions/setup-java@v2
      with:
        distribution: 'microsoft'
        java-version: '17'
    
    - name: CMake configure
      env:
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
      run: cmake . -B build

    - name: CMake generate example
      run: cmake --build build --target build-all-ci

    # TODO: add release build
    - name: CMake build generator and example
      run: cmake --build build --config Debug

    - name: CMake run tests
      run: ctest -C Debug --test-dir build